apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deploy
  labels:
    app: sample
spec:
  replicas: 4
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
      labels:
        app: sample
    spec:
      containers:
      - name: sample
        image: raghudevops30/httpsample:v2
        ports:
        - containerPort: 80
...

---
kind: Service
apiVersion: v1
metadata:
  name: sample-service
spec:
  selector:
    app: sample
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
...
