---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: httpd-rc
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
        - name: httpd
          image: raghudevops30/studentweb:v1 
          imagePullPolicy: Always
...

---
kind: Service
apiVersion: v1
metadata:
  name: web-service
spec:
  selector:
    app: httpd 
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
...
