---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: tomcat-rc
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
        - name: tomcat
          image: raghudevops30/studentapp:v2 
          env: 
            - name: DB_IP
              value: mariadb-service
...

---
kind: Service
apiVersion: v1
metadata:
  name: tomcat-service
spec:
  selector:
    app: tomcat
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer
...
