apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod
spec:
  containers:
    - name: test-container
      image: centos
      command: [ "sleep", "6000" ]
      envFrom:
        - configMapRef:
            name: tomcat-config