apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mariadb-rc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb
          env:
           - name: MYSQL_ROOT_PASSWORD
             value: password
