apiVersion: v1
kind: Pod
metadata:
  name: multi
spec:
  containers:
    - name: db
      image: mariadb
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: password 
    - name: app
      image: centos
      command: ["sleep"]
      args: ["600"]
      
